name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Free disk space
      run: sh docker/free_disk_space.sh 
    - name: Checkout
      uses: actions/checkout@v3
    - name: Download third party
      run: sh docker/download_thirdparty.sh 
    - name: Build the Docker image
      run: |
        BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        DOCKER_TAG= echo "$BRANCH" | sed 's#/#_#g'
        docker build -f docker/Dockerfile -t ocrtoc2024 .
