name: Docker Image CI

on:
  push:
    branches: [ "master", "**" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remove unnecessary files
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image for Mujoco 
      run: |
        echo "GITHUB_HEAD_REF  [$GITHUB_HEAD_REF]"
        echo "GITHUB_REF       [$GITHUB_REF]"
        echo "GITHUB_REF_NAME  [$GITHUB_REF_NAME]"
        DOCKER_TAG="$GITHUB_REF_NAME"
        echo "Tag image as [$DOCKER_TAG]"
        docker build -f docker/Dockerfile -t ocrtoc/ocrtoc2024_mujoco:$DOCKER_TAG .
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Dockerhub
      run: |             
        docker push ocrtoc/ocrtoc2024_mujoco:$DOCKER_TAG
      